version: '3'
services:
  xianyu-agent:
    container_name: xianyu-agent
    image: docker.1ms.run/lmshg/xianyuautoagent:20250516T130259
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./prompts:/app/prompts